frontend: embed     # embedding + positional encoding
frontend_conf:
    embed_dim: 512
    positional_dropout_rate: 0.3

encoder: legonnencoder
encoder_conf:
    output_size: 512
    attention_heads: 4
    linear_units: 1024
    num_blocks: 6
    dropout_rate: 0.3
    positional_dropout_rate: 0.3
    attention_dropout_rate: 0.3
    input_layer: null
    normalize_before: true
    num_target_blocks: 6
    upsampling_rate: 2

decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 1024
    num_blocks: 6
    dropout_rate: 0.3
    positional_dropout_rate: 0.3
    self_attention_dropout_rate: 0.3
    src_attention_dropout_rate: 0.3

model_conf:
    lsm_weight: 0.1
    mt_ctc_weight: 0.3
    length_normalized_loss: false
    share_decoder_input_output_embed: false
    share_encoder_decoder_input_embed: true

num_att_plot: 1
log_interval: 100
num_workers: 2
batch_type: numel
batch_bins: 100000000
accum_grad: 4
max_epoch: 200
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

optim: adam
optim_conf:
    lr: 0.005
    betas:
    - 0.9
    - 0.98
    eps: 0.000000001
    weight_decay: 0.0001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 10000
